from rest_framework.routers import DefaultRouter
from .views import MessageViewSet, ConversationViewSet
from django.urls import path, include

# Create a router and register our viewsets with it.
router = DefaultRouter()
router.register(r'conversations', ConversationViewSet, basename='conversation')
router.register(r'messages', MessageViewSet, basename='message')
# The API URLs are now determined automatically by the router.
urlpatterns = [
    # This will include all the routes generated by the router
    path('', include(router.urls)),
]